name: maven-CI.yml
on:
  push:
    branches:
      - development

jobs:
  CI_TEST_AND_BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Test project Build with Maven
        run: mvn -B test
      - name: Build project with Maven
        run: mvn -B package


